version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/apiProdutosBlack-0.0.1-SNAPSHOT.war apiProdutosBlack-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - apiProdutosBlack-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*